return {
	["Tung Tung Tung Sahur"] = { -- EASY ORDER FOR TUTORIAL, has to be able to complete --
		MoneyPerSecond = 5;
		OrderDifficulty = 1;
		SellPrice = 50;
		YOffset = -0.6;
		WeightPool = {0.5, 3}; -- Min, Max in KG
		CustomOrder = {
			["Strawberry"] = {3,5};
		};
	};

	["Trippi Troppi"] = {
		MoneyPerSecond = 20;
		OrderDifficulty = 1;
		SellPrice = 50;
		YOffset = 0;
		WeightPool = {1, 5};
	};

	["Noobini Burgerini"] = {
		MoneyPerSecond = 2;
		OrderDifficulty = 1;
		SellPrice = 50;
		YOffset = -0.5;
		WeightPool = {0.3, 2};
	};

	["Lirili Larila"] = {
		MoneyPerSecond = 4;
		OrderDifficulty = 1;
		SellPrice = 50;
		YOffset = -0.52;
		WeightPool = {0.8, 4};
	};

	["Bananita Dolphinita"] = {
		MoneyPerSecond = 42;
		OrderDifficulty = 1;
		SellPrice = 50;
		YOffset = 0;
		WeightPool = {2, 8};
	};

	["Boneca Ambalabu"] = {
		MoneyPerSecond = 16;
		OrderDifficulty = 1;
		SellPrice = 50;
		YOffset = -0.5;
		WeightPool = {1, 6};
	};

	["Ballerina Cappuccina"] = {
		MoneyPerSecond = 50;
		OrderDifficulty = 1;
		SellPrice = 50;
		YOffset = -0.6;
		WeightPool = {3, 10};
	};
	
	["Chimpanzini Bananini"] = {
		MoneyPerSecond = 50;
		OrderDifficulty = 1;
		SellPrice = 50;
		YOffset = -0.6;
		WeightPool = {3, 10};
	};

	["Brr Brr Patapim"] = {
		MoneyPerSecond = 13;
		OrderDifficulty = 1;
		SellPrice = 50;
		YOffset = -0.5;
		WeightPool = {0.8, 5};
	};
	
	["Brr Brr Jr"] = {
		MoneyPerSecond = 5000;
		OrderDifficulty = 1;
		SellPrice = 50;
		YOffset = -0.5;
		WeightPool = {0.5, 3};
	};

	["Trulimero Trulichina"] = {
		MoneyPerSecond = 3;
		OrderDifficulty = 1;
		SellPrice = 50;
		YOffset = 1.25;
		WeightPool = {0.5, 2.5};
	};

	["Pot Hotspot"] = {
		MoneyPerSecond = 160;
		OrderDifficulty = 1;
		SellPrice = 50;
		YOffset = 1.25;
		WeightPool = {5, 15};
	};

	["Bombadilo Crocodilo"] = {
		MoneyPerSecond = 475;
		OrderDifficulty = 1;
		SellPrice = 1.25;
		YOffset = -0.38;
		WeightPool = {5, 16};
	};

	["Cappuccino Assassino"] = {
		MoneyPerSecond = 17;
		OrderDifficulty = 1;
		SellPrice = 50;
		YOffset = -0.38;
		WeightPool = {2, 8};
	};
	
	["Loudini Speakerini"] = {
		MoneyPerSecond = 475;
		OrderDifficulty = 1;
		SellPrice = 1.25;
		YOffset = -0.38;
		WeightPool = {3, 12};
	};
	
	

	["Bombombini Gusini"] = {
		MoneyPerSecond = 250;
		OrderDifficulty = 1;
		SellPrice = 50;
		YOffset = 1.25;
		WeightPool = {8, 20};
	};
}