return {
	["Sandstorm"] = {
		["Description"] = "Chance for plants/brainrots to mutate into Sandy!";
		["MutationName"] = "Sandy";
		["Duration"] = 160; -- should  be 160 for most.
		-- setup duration here probably haha
		Icon = "rbxassetid://111315750925394";
		Chance = 100;
	};
	["Snowing"] = {
		["Description"] = "Chance for plants/brainrots to mutate into Chilled!";
		["MutationName"] = "Chilled";
		["Duration"] = 160; -- should  be 160 for most.
		-- setup duration here probably haha
		Icon = "rbxassetid://114289644982488";
		Chance = 100;
	};
	
	
	["Heatwave"] = {
		["Description"] = "Chance for plants/brainrots to mutate into Burning!";
		["MutationName"] = "Burning";
		["Duration"] = 160; -- should  be 160 for most.
		-- setup duration here probably haha
		Icon = "rbxassetid://84650932977330";
		Chance = 100;
	};
	-- thunder rbxassetid://89344229152629
	["Rain"] = {
		["Description"] = "Chance for plants/brainrots to mutate into Wet!";
		["MutationName"] = "Wet";
		["Duration"] = 160; -- should  be 160 for most.
		-- setup duration here probably haha
		Icon = "rbxassetid://109622537679215";
		Chance = 100;
	};
	
	
	["Spooky"] = {
		["Description"] = "Chance for plants/brainrots to mutate into Haunted!";
		["MutationName"] = "Haunted";
		["Duration"] = 160; -- should  be 160 for most.
		-- setup duration here probably haha
		Icon = "rbxassetid://109622537679215";
		Chance = 100;
	};
}

