return {
	["Strawberry Seed"] = {
		Placeable = true;
		GrowthTime = 20;
		Product = "Strawberry";
		Type = "Plant";
		Rarity = "Rare";
		BuyPrice = 35;
		SellPrice = 14;
		hex = "#8D2130";
		BestStock = 6;
		MinimumStock = 2;
		Layout = 2;
		PurchaseID = 3518307917;
	};

	["Carrot Seed"] = {
		Placeable = true;
		GrowthTime = 9;
		Product = "Carrot";
		Type = "Plant";
		Rarity = "Rare";
		BuyPrice = 10;
		SellPrice = 5;
		hex = "#8D2130";
		BestStock = 20;
		MinimumStock = 8;
		Layout = 1;
		PurchaseID = 3518307960;
	};
	
	["Pumpkin Seed"] = {
		Placeable = true;
		GrowthTime = 35;
		Product = "Pumpkin";
		Type = "Plant";
		Rarity = "Epic";
		BuyPrice = 300;
		SellPrice = 55;
		hex = "#8D2130";
		BestStock = 4;
		MinimumStock = 0;
		Layout = 2;
		PurchaseID = 3518307848;
	};
	
	["Melon Seed"] = {
		Placeable = true;
		GrowthTime = 40;
		Product = "Melon";
		Type = "Plant";
		Rarity = "Epic";
		BuyPrice = 400;
		SellPrice = 70;
		hex = "#5DBB63";
		BestStock = 3;
		MinimumStock = 0;
		Layout = 2;
		PurchaseID = 0; -- Add your Robux product ID here
	};
	
	["Mango Seed"] = {
		Placeable = true;
		GrowthTime = 60;
		Product = "Mango";
		Type = "Plant";
		Rarity = "Secret";
		BuyPrice = 35;
		SellPrice = 7;
		hex = "#8D2130";
		BestStock = 1;
		MinimumStock = 0;
		Layout = 2;
		PurchaseID = 3518307090;
	};
	
	["Red Apple Seed"] = {
		Placeable = true;
		GrowthTime = 60;
		Product = "Red Apple";
		Type = "Plant";
		Rarity = "Legendary";
		BuyPrice = 35;
		SellPrice = 7;
		hex = "#8D2130";
		BestStock = 3;
		MinimumStock = 0;
		Layout = 2;
		PurchaseID = 3518307655;
	};
	
	["Green Apple Seed"] = {
		Placeable = true;
		GrowthTime = 60;
		Product = "Green Apple";
		Type = "Plant";
		Rarity = "Mythic";
		BuyPrice = 35;
		SellPrice = 7;
		hex = "#8D2130";
		BestStock = 3;
		MinimumStock = 0;
		Layout = 2;
		PurchaseID = 3518307502;
	};

	["Cactus Seed"] = {
		Placeable = true;
		GrowthTime = 60;
		Product = "Cactus";
		Type = "Plant";
		Rarity = "Godly";
		BuyPrice = 35;
		SellPrice = 7;
		hex = "#8D2130";
		BestStock = 3;
		MinimumStock = 0;
		Layout = 2;
		PurchaseID = 3518307242;
	};

	["Chili Pepper Seed"] = {
		Placeable = true;
		GrowthTime = 50;
		Product = "Chili Pepper";
		Type = "Plant";
		Rarity = "Legendary";
		BuyPrice = 500;
		SellPrice = 85;
		hex = "#C41E3A";
		BestStock = 3;
		MinimumStock = 0;
		Layout = 2;
		PurchaseID = 0; -- Add your Robux product ID here
	};

	-- FRUITS --
	["Strawberry"] = {
		SellPrice = 10;
		Type = "Fruit";
		Rarity = "Rare";
		hex = "#8D2130";
		WeightPool = {0.21, 0.5}; -- Strawberries are light
		Layout = 2;
	};
	
	["Pumpkin"] = {
		SellPrice = 55;
		Type = "Fruit";
		Rarity = "Epic";
		hex = "#FF7518";
		WeightPool = {4.6, 7.2}; -- Strawberries are light
		Layout = 3;
	};
	
	["Melon"] = {
		SellPrice = 55;
		Type = "Fruit";
		Rarity = "Epic";
		hex = "#FF7518";
		WeightPool = {4.6, 7.2}; -- Strawberries are light
		Layout = 3;
	};
	
	["Carrot"] = {
		SellPrice = 35;
		Type = "Fruit";
		Rarity = "Rare";
		hex = "#f59b0c";
		WeightPool = {1.2, 2};
		Layout = 1;
	};
	
	["Red Apple"] = {
		SellPrice = 250;
		Type = "Fruit";
		Rarity = "Legendary";
		hex = "#f59b0c";
		WeightPool = {2, 4.2};
		Layout = 3;
	};
	
	["Green Apple"] = {
		SellPrice = 250;
		Type = "Fruit";
		Rarity = "Mythic";
		hex = "#f59b0c";
		WeightPool = {2, 4.2};
		Layout = 4;
	};

	["Cactus"] = {
		SellPrice = 250;
		Type = "Fruit";
		Rarity = "Godly";
		hex = "#f59b0c";
		WeightPool = {2, 4.2};
		Layout = 5;
	};

	["Chili Pepper"] = {
		SellPrice = 200;
		Type = "Fruit";
		Rarity = "Legendary";
		hex = "#C41E3A";
		WeightPool = {1.5, 3.5};
		Layout = 3;
	};
	
	["Mango"] = {
		SellPrice = 250;
		Type = "Fruit";
		Rarity = "Secret";
		hex = "#f59b0c";
		WeightPool = {10, 14.5};
		Layout = 6;
	};
	
	-- potions --
	["Brainrot Potion"] = {
		Rarity = "Godly";
		Type = "Potion";
	};
	
	["Mutation Potion"] = {
		Rarity = "Godly";
		Type = "Potion";
	};
	
	["Size Potion"] = {
		Rarity = "Godly";
		Type = "Potion";
	};
	
	["Speed Potion"] = {
		Rarity = "Godly";
		Type = "Potion";
	};
	
	["Sigma Potion"] = {
		Rarity = "Secret";
		Type = "Potion";
	};
}